modLoader="javafml"
loaderVersion="[40,)"
license="GPL3"

[[mods]]
modId="nukacraft"
version="1.2.1"
displayName="Nuka Craft"
updateJSONURL=""
displayURL=""
logoFile="logo.png"
authors="Dayton, Jetug"
description="NukaCraft - This is a global mod that opens up the possibility for players to be transported to the wastelands and feel like a wanderer. Collect weapons, find Power Armor sets and don't let the wastelands swallow you up"

[[dependencies.nukacraft]]
modId="forge"
mandatory=true
versionRange="[40.2.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.nukacraft]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.nukacraft]]
modId="framework"
mandatory=true
versionRange="[0.4.2,)"
ordering="NONE"
side="BOTH"
#[[dependencies.nukacraft]]
#modId="cgm"
#mandatory=true
#versionRange="[1.3.3,)"
#ordering="AFTER"
#side="BOTH"

[modproperties.nukacraft]
    catalogueImageIcon=""
