modLoader="javafml"
loaderVersion="[40,)"
license="GPL3"

[[mods]]
modId="nukacraft"
version="${file.jarVersion}"
displayName="Nuka Craft"
updateJSONURL=""
displayURL=""
logoFile="logo.png"
authors="Dayton, Jetug"
credits = "MrCrayfish, Hunternif, AzureDoom"
description="NukaCraft - This is a global mod that will bring some nuclear dust to the world of Minecraft. Collect weapons, find Power Armor sets and don't let the wastelands swallow you up"

[[dependencies.nukacraft]]
modId="forge"
mandatory=true
versionRange="[46, 48)"
ordering="NONE"
side="BOTH"
[[dependencies.nukacraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.nukacraft]]
modId="azurelib"
mandatory=true
versionRange="[2.0.20,)"
ordering="AFTER"
side="BOTH"
[[dependencies.nukacraft]]
modId="chassis_core"
mandatory=true
versionRange="[1.20.1-2.5.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.nukacraft]]
modId="ntgl"
mandatory=true
versionRange="[1.20.1-1.3.1,)"
ordering="AFTER"
side="BOTH"

[modproperties.nukacraft]
    catalogueImageIcon=""
