modLoader="javafml"
loaderVersion="[40,)"
license="GPL3"

[[mods]]
modId="nukacraft"
version="${file.jarVersion}"
displayName="Nuka Craft"
updateJSONURL=""
displayURL=""
logoFile="logo.png"
authors="Dayton, Jetug"
credits = "MrCrayfish, Hunternif, AzureDoom"
description="NukaCraft - This is a global mod that will bring some nuclear dust to the world of Minecraft. Collect weapons, find Power Armor sets and don't let the wastelands swallow you up"

[[dependencies.nukacraft]]
modId="forge"
mandatory=true
versionRange="[40.2.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.nukacraft]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.nukacraft]]
modId="chassis_core"
mandatory=true
versionRange="[2.2.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.nukacraft]]
modId="ntgl"
mandatory=true
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.nukacraft]]
modId="azurelib"
mandatory=true
versionRange="[1.0.23,)"
ordering="AFTER"
side="BOTH"

[modproperties.nukacraft]
    catalogueImageIcon=""
